version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emission_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script
    ports:
      - "5433:5432"
    networks:
      - emission_network

  synthetic_data_generation:
    build: .
    container_name: python_container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: emission_db
    networks:
      - emission_network
    command: ["python", "synthetic_data_generation/generate_data.py"]

networks:
  emission_network:
    driver: bridge
